---
- name: this is httpd
  hosts: all
  become: true
  tasks:
  - name: httpd installation
    package:
      name: httpd
      state: latest
  - name: copy the index file
    copy:
      src: index.html
      dest: /var/www/html/
  - name: service httpd
    service:
      name: httpd
      state: started
